<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use App\Models\City;
use App\Models\Village;

class VillagesSeeder extends Seeder
{
    public function run(): void
    {
        // تأكد من وجود فلسطين
        $palestine = Country::where('iso_code', 'PS')->first();
        if (!$palestine) {
            $this->command?->warn('Palestine country not found. Run CountriesSeeder first.');
            return;
        }

        // تعريف القرى لكل مدينة مطلوبة
        $data = [
            'ابو غوش' => [
                ['ar' => 'بيت نقوبا', 'en' => 'Bayt Naquba'],
                ['ar' => 'عين رافا', 'en' => "'Ain Rafa"],
                ['ar' => 'عين نقوبا', 'en' => "'Ain Naquba"],
            ],
            'اريحا' => [
                ['ar' => 'الجفتلك', 'en' => 'Al-Jiftlik'],
                ['ar' => 'الزبيدات', 'en' => 'Az-Zubeidat'],
                ['ar' => 'العوجا', 'en' => 'Al-Auja'],
                ['ar' => 'النبي موسى', 'en' => 'An-Nabi Musa'],
                ['ar' => 'النويعمة', 'en' => "An-Nuway'ima"],
                ['ar' => 'حي الخديوي', 'en' => 'Al-Khedewi Neighborhood'],
                ['ar' => 'حي القصب', 'en' => 'Al-Qasab Neighborhood'],
                ['ar' => 'عين الديوك الفوقا', 'en' => "'Ain ad-Duyuk al-Fauqa"],
                ['ar' => 'فروش بيت دجن', 'en' => 'Froush Beit Dajan'],
                ['ar' => 'فصايل', 'en' => 'Fasayil'],
                ['ar' => 'مخيم عقبة جبر', 'en' => 'Aqbat Jaber Camp'],
                ['ar' => 'مخيم عين السلطان', 'en' => 'Ein as-Sultan Camp'],
                ['ar' => 'اريحا', 'en' => 'Jericho'],
                ['ar' => 'شارع القدس', 'en' => 'Jerusalem Street'],
                ['ar' => 'شارع فلسطين', 'en' => 'Palestine Street'],
                ['ar' => 'وسط البلد', 'en' => 'Downtown'],
                ['ar' => 'الديوك', 'en' => 'Ad-Duyuk'],
                ['ar' => 'النويعمة', 'en' => "An-Nuway'ima"],
                ['ar' => 'حي البياض', 'en' => 'Al-Biyad Neighborhood'],
                ['ar' => 'شارع الاستراحة', 'en' => 'Istiraha Street'],
                ['ar' => 'شارع البنوك', 'en' => 'Banks Street'],
                ['ar' => 'شارع المغطس', 'en' => 'Al-Maghtas Street'],
                ['ar' => 'شارع المنتزهات', 'en' => 'Parks Street'],
                ['ar' => 'شارع عمان', 'en' => 'Amman Street'],
                ['ar' => 'شارع قصر بن هشام', 'en' => 'Qasr Ibn Hisham Street'],
                ['ar' => 'عقبة جبر', 'en' => 'Aqbat Jaber'],
                ['ar' => 'عين السلطان', 'en' => 'Ein as-Sultan'],
                ['ar' => 'كتف الواد', 'en' => 'Katf al-Wad'],
                ['ar' => 'مرج الغزال', 'en' => 'Marj al-Ghazal'],
                ['ar' => 'مرج نعجة', 'en' => "Marj Na'ja"],
            ],
            'الجليل' => [
                ['ar' => 'ابطن', 'en' => 'Ibtin'],
                ['ar' => 'ابو سنان', 'en' => 'Abu Sinan'],
                ['ar' => 'اكسال', 'en' => 'Iksal'],
                ['ar' => 'البعنة', 'en' => "Al-Bi'na"],
                ['ar' => 'الجش', 'en' => 'Al-Jish'],
                ['ar' => 'الحسينية', 'en' => 'Al-Husayniya'],
                ['ar' => 'الحلف', 'en' => 'Al-Halaf'],
                ['ar' => 'الخضيرة', 'en' => 'Al-Khudeira'],
                ['ar' => 'الخوالد', 'en' => 'Al-Khawaled'],
                ['ar' => 'الدحي', 'en' => 'Ad-Dahi'],
                ['ar' => 'الرامة', 'en' => 'Ar-Rama'],
                ['ar' => 'الريحانية', 'en' => 'Ar-Rayhaniya'],
                ['ar' => 'الرينة', 'en' => "Ar-Rina"],
                ['ar' => 'الزرازير', 'en' => 'Az-Zarazir'],
                ['ar' => 'الشيخ دنون', 'en' => 'Sheikh Danun'],
                ['ar' => 'الطيبة الزعبية', 'en' => "At-Tayba az-Za'biya"],
                ['ar' => 'العزير', 'en' => "Al-'Azayir"],
                ['ar' => 'الفريديس', 'en' => 'Al-Furaydis'],
                ['ar' => 'الكرمل', 'en' => 'Al-Karmel'],
                ['ar' => 'الكعبية', 'en' => "Al-Ka'biya"],
                ['ar' => 'المزرعة (قضاء عكا)', 'en' => "Al-Mazra'a (Acre District)"],
                ['ar' => 'المشهد', 'en' => 'Al-Mashhad'],
                ['ar' => 'المغار', 'en' => 'Al-Maghar'],
                ['ar' => 'المقيبلة', 'en' => 'Al-Muqeibila'],
                ['ar' => 'الناصرة', 'en' => 'An-Nasira'],
                ['ar' => 'الناصرة العليا', 'en' => 'Upper Nazareth'],
                ['ar' => 'الناصرة', 'en' => 'An-Nasira'],
                ['ar' => 'الناعورة', 'en' => "An-Na'ura"],
                ['ar' => 'ام الغنم', 'en' => 'Umm al-Ghanam'],
                ['ar' => 'اور عكيبا', 'en' => 'Or Akiva'],
                ['ar' => 'بردس حنا', 'en' => 'Pardes Hanna'],
                ['ar' => 'بسمة طبعون', 'en' => "Basmat Tab'un"],
                ['ar' => 'بعينة النجيدات', 'en' => "Bi'ina an-Nujaydat"],
                ['ar' => 'بيت جن', 'en' => 'Bayt Jann'],
                ['ar' => 'بير الامير', 'en' => 'Bir al-Amir'],
                ['ar' => 'بير المكسور', 'en' => 'Bir al-Maksur'],
                ['ar' => 'بيسان', 'en' => 'Bisan'],
                ['ar' => 'ترشيحا', 'en' => 'Tarshiha'],
                ['ar' => 'جديدة المكر', 'en' => 'Jadeida al-Makr'],
                ['ar' => 'جسر الزرقا', 'en' => 'Jisr az-Zarqa'],
                ['ar' => 'جش', 'en' => 'Jash'],
                ['ar' => 'جولس', 'en' => 'Julis'],
                ['ar' => 'حي الصفافرة', 'en' => 'As-Safafira Neighborhood'],
                ['ar' => 'حيفا', 'en' => 'Haifa'],
                ['ar' => 'دالية الكرمل', 'en' => 'Daliyat al-Karmel'],
                ['ar' => 'دبورية', 'en' => 'Daburiya'],
                ['ar' => 'دير الاسد', 'en' => 'Deir al-Asad'],
                ['ar' => 'دير حنا', 'en' => 'Deir Hanna'],
                ['ar' => 'راس العين', 'en' => "Ras al-'Ain"],
                ['ar' => 'راس علي', 'en' => 'Ras Ali'],
                ['ar' => 'رمانة', 'en' => 'Rummana'],
                ['ar' => 'زخرون يعقوب', 'en' => "Zikhron Ya'akov"],
                ['ar' => 'ساجور', 'en' => 'Sajur'],
                ['ar' => 'سخنين', 'en' => 'Sakhnin'],
                ['ar' => 'سولم', 'en' => 'Sulam'],
                ['ar' => 'شعب', 'en' => "Sha'ab"],
                ['ar' => 'شفاعمرو', 'en' => "Shefa-'Amr"],
                ['ar' => 'شلومي', 'en' => 'Shlomi'],
                ['ar' => 'صفد', 'en' => 'Safed'],
                ['ar' => 'صندلة', 'en' => 'Sandala'],
                ['ar' => 'ضميده', 'en' => 'Dumayda'],
                ['ar' => 'طباش', 'en' => 'Tabash'],
                ['ar' => 'طبريا', 'en' => 'Tiberias'],
                ['ar' => 'طرعان', 'en' => "Tur'an"],
                ['ar' => 'طمرة', 'en' => 'Tamra'],
                ['ar' => 'طمرة الزعبية', 'en' => "Tamra az-Za'biya"],
                ['ar' => 'طوبا الهيب', 'en' => 'Tuba al-Heib'],
                ['ar' => 'طيرة الكرمل', 'en' => 'Tirat al-Karmel'],
                ['ar' => 'عبلين', 'en' => "I'billin"],
                ['ar' => 'عتليت', 'en' => 'Atlit'],
                ['ar' => 'عرابة البطوف', 'en' => 'Arraba al-Battuf'],
                ['ar' => 'عرب الشبلي', 'en' => 'Arab ash-Shibli'],
                ['ar' => 'عرب النعيم', 'en' => "Arab an-Na'im"],
                ['ar' => 'عرب الهيب', 'en' => 'Arab al-Heib'],
                ['ar' => 'عسفيا', 'en' => 'Isfiya'],
                ['ar' => 'عفولة', 'en' => 'Afula'],
                ['ar' => 'عقبرا', 'en' => 'Aqbara'],
                ['ar' => 'عكا', 'en' => "'Akka (Acre)"],
                ['ar' => 'عيلبون', 'en' => 'Aylabon'],
                ['ar' => 'عيلوط', 'en' => "'Ilut"],
                ['ar' => 'عين الاسد', 'en' => "'Ain al-Asad"],
                ['ar' => 'عين حوض', 'en' => "'Ain Hawd"],
                ['ar' => 'عين ماهل', 'en' => "'Ain Mahil"],
                ['ar' => 'فرديس', 'en' => 'Fureidis'],
                ['ar' => 'قرية نين', 'en' => 'Nin Village'],
                ['ar' => 'قيسارية', 'en' => 'Qaysariya (Caesarea)'],
                ['ar' => 'كابول', 'en' => 'Kabul'],
                ['ar' => 'كرمئيل', 'en' => 'Karmiel'],
                ['ar' => 'كريات اتا', 'en' => 'Kiryat Ata'],
                ['ar' => 'كريات بياليك', 'en' => 'Kiryat Bialik'],
                ['ar' => 'كريات طبعون', 'en' => "Kiryat Tiv'on"],
                ['ar' => 'كريات موتسكن', 'en' => 'Kiryat Motzkin'],
                ['ar' => 'كريات يام', 'en' => 'Kiryat Yam'],
                ['ar' => 'كسرى', 'en' => 'Kisra'],
                ['ar' => 'كفر سميع', 'en' => "Kafr Sumei"],
                ['ar' => 'كفر كما', 'en' => 'Kfar Kama'],
                ['ar' => 'كفر كنا', 'en' => 'Kafr Kanna'],
                ['ar' => 'كفر مصر', 'en' => 'Kafr Misr'],
                ['ar' => 'كفر مندا', 'en' => 'Kafr Manda'],
                ['ar' => 'كفرياسيف', 'en' => 'Kafr Yasif'],
                ['ar' => 'كفر ياسيف', 'en' => 'Kafr Yasif'],
                ['ar' => 'كمانة', 'en' => 'Kammana'],
                ['ar' => 'كوكب ابو الهيجا', 'en' => 'Kaukab Abu al-Hija'],
                ['ar' => 'كيبوتس عوفر', 'en' => "Kibbutz 'Ofer"],
                ['ar' => 'مجد الكروم', 'en' => 'Majd al-Krum'],
                ['ar' => 'مجدال هعيمك', 'en' => 'Migdal HaEmek'],
                ['ar' => 'معالوت ترشيحا', 'en' => "Ma'alot-Tarshiha"],
                ['ar' => 'معجان ميخائيل', 'en' => "Ma'ayan Mikhael"],
                ['ar' => 'معليا', 'en' => "Mi'ilya"],
                ['ar' => 'منشية الزبدة', 'en' => "Manshiyat az-Zubda"],
                ['ar' => 'ناعورة', 'en' => "Na'ura"],
                ['ar' => 'نحف', 'en' => 'Nahf'],
                ['ar' => 'نهاريا', 'en' => 'Nahariya'],
                ['ar' => 'نوف هجليل', 'en' => 'Nof HaGalil'],
                ['ar' => 'وادي الحمام', 'en' => 'Wadi al-Hamam'],
                ['ar' => 'وادي سلامة', 'en' => 'Wadi Salameh'],
                ['ar' => 'يافة الناصرة', 'en' => 'Yafa an-Nasra'],
                ['ar' => 'يانوح جت', 'en' => 'Yanuh-Jat'],
                ['ar' => 'يركا', 'en' => 'Yarka'],
                ['ar' => 'يوكنعام', 'en' => 'Yokneam'],
            ],
            'الجولان' => [
                ['ar' => 'الغجر', 'en' => 'Al-Ghajar'],
                ['ar' => 'المطلة', 'en' => 'Metula'],
                ['ar' => 'اورتال', 'en' => 'Ortal'],
                ['ar' => 'بقعاثا', 'en' => "Buq'ata"],
                ['ar' => 'بقيعه', 'en' => "Baqi'a"],
                ['ar' => 'حرفيش', 'en' => 'Hurfeish'],
                ['ar' => 'روش بينا', 'en' => 'Rosh Pinna'],
                ['ar' => 'شار', 'en' => "Sha'ar"],
                ['ar' => 'شامير', 'en' => 'Shamir'],
                ['ar' => 'شعل', 'en' => "Sha'al"],
                ['ar' => 'طوبا الزنغرية', 'en' => 'Tuba-Zangariya'],
                ['ar' => 'عرب العرامشة', 'en' => 'Arab al-Aramshe'],
                ['ar' => 'علما', 'en' => 'Alma'],
                ['ar' => 'عين قنيا', 'en' => 'Ein Qiniya'],
                ['ar' => 'فسوطة', 'en' => 'Fassuta'],
                ['ar' => 'كريات شمونه', 'en' => 'Kiryat Shmona'],
                ['ar' => 'كيتسيريم', 'en' => 'Katzrin'],
                ['ar' => 'مجدل شمس', 'en' => 'Majdal Shams'],
                ['ar' => 'مسعده', 'en' => "Mas'ada"],
                ['ar' => 'ناحل حرمون', 'en' => 'Nahal Hermon'],
                ['ar' => 'نحميم', 'en' => 'Nahmim'],
                ['ar' => 'يسود همعلا', 'en' => "Yesod HaMa'ala"],
            ],
            'الخليل' => [
                ['ar' => 'اذنا', 'en' => 'Idhna'],
                ['ar' => 'الخليل', 'en' => 'Hebron'],
                ['ar' => 'الريحية', 'en' => 'Ar-Rihiya'],
                ['ar' => 'السموع', 'en' => "As-Samu'"],
                ['ar' => 'السموع', 'en' => "As-Samu'"],
                ['ar' => 'الشيوخ', 'en' => "Ash-Shuyukh"],
                ['ar' => 'الظاهرية', 'en' => 'Adh-Dhahiriya'],
                ['ar' => 'الظاهرية −رابود', 'en' => 'Adh-Dhahiriya - Rabud'],
                ['ar' => 'العروب', 'en' => "Al-'Arrub"],
                ['ar' => 'بني نعيم', 'en' => "Bani Na'im"],
                ['ar' => 'بيت امر', 'en' => 'Beit Ummar'],
                ['ar' => 'بيت أولا', 'en' => 'Bayt Ula'],
                ['ar' => 'بيت اولا', 'en' => 'Bayt Ula'],
                ['ar' => 'بيت عوا', 'en' => "Bayt 'Awwa"],
                ['ar' => 'بيت عينون', 'en' => "Bayt 'Einun"],
                ['ar' => 'بيت كاحل', 'en' => 'Bayt Kahil'],
                ['ar' => 'ترقوميا', 'en' => 'Tarqumiya'],
                ['ar' => 'تفوح', 'en' => 'Tafuh'],
                ['ar' => 'حلحول', 'en' => 'Halhul'],
                ['ar' => 'خاراس', 'en' => 'Kharas'],
                ['ar' => 'خلة الدار', 'en' => 'Khillet ad-Dar'],
                ['ar' => 'دورا', 'en' => 'Dura'],
                ['ar' => 'دورا-ابو العسجا', 'en' => 'Dura - Abu al-Asja'],
                ['ar' => 'دورا-البرج', 'en' => 'Dura - Al-Burj'],
                ['ar' => 'دورا-الصرة', 'en' => 'Dura - As-Sura'],
                ['ar' => 'دورا-المورق', 'en' => 'Dura - Al-Mawraq'],
                ['ar' => 'دورا-الهجرة', 'en' => 'Dura - Al-Hijra'],
                ['ar' => 'دورا-بيت الروش التحتا', 'en' => 'Dura - Bayt ar-Rush at-Tahta'],
                ['ar' => 'دورا-بيت الروش الفوقا', 'en' => 'Dura - Bayt ar-Rush al-Fauqa'],
                ['ar' => 'دورا-بيت مرسم', 'en' => 'Dura - Bayt Marsam'],
                ['ar' => 'دورا-تجمع الكوم', 'en' => 'Dura - Al-Kum Cluster'],
                ['ar' => 'دورا-خربة المجد', 'en' => 'Dura - Khirbet al-Majd'],
                ['ar' => 'دورا-دير العسل التحتا', 'en' => "Dura - Deir al-Asal at-Tahta"],
                ['ar' => 'دورا-دير العسل الفوقا', 'en' => 'Dura - Deir al-Asal al-Fauqa'],
                ['ar' => 'دورا-دير سامت', 'en' => 'Dura - Deir Samit'],
                ['ar' => 'دورا-سكة', 'en' => 'Dura - Sikka'],
                ['ar' => 'دورا-كرزة', 'en' => 'Dura - Karza'],
                ['ar' => 'سعير', 'en' => "Sa'ir"],
                ['ar' => 'صوريف', 'en' => 'Surif'],
                ['ar' => 'عرب الرماضين', 'en' => 'Arab ar-Ramadin'],
                ['ar' => 'مخيم الفوار', 'en' => 'Al-Fawwar Camp'],
                ['ar' => 'نوبا', 'en' => 'Nuba'],
                ['ar' => 'واد السمن', 'en' => 'Wadi as-Saman'],
                ['ar' => 'يطا', 'en' => 'Yatta'],
                // إضافات أحياء وقرى مدينة الخليل
                ['ar' => 'باب زاوية', 'en' => 'Bab al-Zawiya'],
                ['ar' => 'جبل شريف', 'en' => 'Jabal Sharif'],
                ['ar' => 'دوار المختار', 'en' => 'Mukhtar Roundabout'],
                ['ar' => 'لوزا', 'en' => 'Al-Lawza'],
                ['ar' => 'الخليل - مدينة الخليل', 'en' => 'Hebron - Hebron City'],
                ['ar' => 'مدينة الخليل−ابو اكتيلة', 'en' => 'Hebron City - Abu Iktayla'],
                ['ar' => 'مدينة الخليل−البلدة القديمة', 'en' => 'Hebron City - Old City'],
                ['ar' => 'مدينة الخليل−الجلدة', 'en' => 'Hebron City - Al-Jilda'],
                ['ar' => 'مدينة الخليل−الحاوز الأول', 'en' => 'Hebron City - First Water Tank'],
                ['ar' => 'مدينة الخليل− الحاوز الثاني', 'en' => 'Hebron City - Second Water Tank'],
                ['ar' => 'مدينة الخليل− الحرس', 'en' => 'Hebron City - Al-Haras'],
                ['ar' => 'مدينة الخليل−الخليل-دوار المنارة', 'en' => 'Hebron City - Manara Roundabout'],
                ['ar' => 'مدينة الخليل−الخليل-وسط البلد', 'en' => 'Hebron City - Downtown'],
                ['ar' => 'مدينة الخليل−المحاور', 'en' => 'Hebron City - Al-Mahawer'],
                ['ar' => 'مدينة الخليل−المنطقة الجنوبية', 'en' => 'Hebron City - Southern Area'],
                ['ar' => 'مدينة الخليل−بير المحجر', 'en' => 'Hebron City - Bir al-Mahjar'],
                ['ar' => 'مدينة الخليل−بير المحجر', 'en' => 'Hebron City - Bir al-Mahjar'],
                ['ar' => 'مدينة الخليل−جبل ابو رمان', 'en' => 'Hebron City - Jabal Abu Rumman'],
                ['ar' => 'مدينة الخليل−جبل الرحمة', 'en' => 'Hebron City - Jabal ar-Rahma'],
                ['ar' => 'مدينة الخليل−حارة الشيخ', 'en' => 'Hebron City - Haret ash-Sheikh'],
                ['ar' => 'مدينة الخليل−حي الجامعه', 'en' => 'Hebron City - University Neighborhood'],
                ['ar' => 'مدينة الخليل−دوار ابن رشد', 'en' => 'Hebron City - Ibn Rushd Roundabout'],
                ['ar' => 'مدينة الخليل−دوار ابن رشد', 'en' => 'Hebron City - Ibn Rushd Roundabout'],
                ['ar' => 'مدينة الخليل−دوار الصحه', 'en' => 'Hebron City - Al-Sihha Roundabout'],
                ['ar' => 'مدينة الخليل−دويربان', 'en' => 'Hebron City - Dweirban'],
                ['ar' => 'مدينة الخليل−راس الجورة', 'en' => 'Hebron City - Ras al-Jura'],
                ['ar' => 'مدينة الخليل−سنجر', 'en' => 'Hebron City - Sanjar'],
                ['ar' => 'مدينة الخليل−شارع السلام', 'en' => 'Hebron City - Salam Street'],
                ['ar' => 'مدينة الخليل−شارع الشلالة', 'en' => 'Hebron City - Shallala Street'],
                ['ar' => 'مدينة الخليل−شارع العدل', 'en' => 'Hebron City - Justice Street'],
                ['ar' => 'مدينة الخليل−شارع الملك فيصل', 'en' => 'Hebron City - King Faisal Street'],
                ['ar' => 'مدينة الخليل−شارع بير السبع', 'en' => 'Hebron City - Beersheba Street'],
                ['ar' => 'مدينة الخليل−شعابة', 'en' => "Hebron City - Sha'aba"],
                ['ar' => 'مدينة الخليل− ضاحية البلدية', 'en' => 'Hebron City - Municipality Suburb'],
                ['ar' => 'مدينة الخليل−ضاحية الرامة', 'en' => 'Hebron City - Ar-Rama Suburb'],
                ['ar' => 'مدينة الخليل−عقبة تفوح', 'en' => 'Hebron City - Aqbat Tafuh'],
                ['ar' => 'مدينة الخليل−عيصى', 'en' => "Hebron City - Aissa"],
                ['ar' => 'مدينة الخليل−عين سارة', 'en' => 'Hebron City - Ein Sarah'],
                ['ar' => 'مدينة الخليل−فرش الهوى', 'en' => 'Hebron City - Farsh al-Hawa'],
                ['ar' => 'مدينة الخليل−قرن الثور', 'en' => 'Hebron City - Qarn ath-Thawr'],
                ['ar' => 'مدينة الخليل-قيزون', 'en' => 'Hebron City - Qayzun'],
                ['ar' => 'مدينة الخليل−نمرة', 'en' => 'Hebron City - Nimra'],
                ['ar' => 'مدينة الخليل−واد التفاح', 'en' => 'Hebron City - Wadi at-Tuffah'],
                ['ar' => 'مدينة الخليل−واد الزرازير', 'en' => 'Hebron City - Wadi az-Zarazir'],
                ['ar' => 'مدينة الخليل−واد الغروس', 'en' => 'Hebron City - Wadi al-Ghrous'],
                ['ar' => 'مدينة الخليل−واد الهرية', 'en' => 'Hebron City - Wadi al-Hariyya'],
                ['ar' => 'مربعة سبتة', 'en' => "Marba'at Sabta"],
                ['ar' => 'مفرق الصاحب', 'en' => 'Mafraq as-Sahib'],
                ['ar' => 'واد القطع', 'en' => "Wadi al-Qata'"],
            ],
            // الداخل
            'الداخل' => [
                ['ar' => 'الناصرة', 'en' => 'An-Nasira (Nazareth)'],
                ['ar' => 'حجاجرة', 'en' => 'Hajjajra'],
            ],
            // القدس
            'القدس' => [
                ['ar' => 'ابو الطور', 'en' => 'Abu Tor'],
                ['ar' => 'الباب الجديد', 'en' => 'New Gate'],
                ['ar' => 'البلدة القديمة', 'en' => 'Old City'],
                ['ar' => 'التلة الفرنسية', 'en' => 'French Hill'],
                ['ar' => 'الثوري', 'en' => 'Ath-Thuri'],
                ['ar' => 'الجامعة العبرية', 'en' => 'Hebrew University'],
                ['ar' => 'الشيخ جراح', 'en' => 'Sheikh Jarrah'],
                ['ar' => 'الصوانة', 'en' => 'As-Suwana'],
                ['ar' => 'الطور', 'en' => 'At-Tur'],
                ['ar' => 'الطوري', 'en' => 'At-Turi'],
                ['ar' => 'العيساوية', 'en' => "Al-'Isawiya"],
                ['ar' => 'القسطل', 'en' => 'Al-Qastal'],
                ['ar' => 'القطمون', 'en' => 'Qatamon'],
                ['ar' => 'المالحة', 'en' => 'Malha'],
                ['ar' => 'المحطة المركزية', 'en' => 'Central Bus Station'],
                ['ar' => 'المسكوبية', 'en' => 'Russian Compound (Muscovia)'],
                ['ar' => 'المصرارة', 'en' => 'Musrara'],
                ['ar' => 'المطلع', 'en' => "Al-Mutalla'"],
                ['ar' => 'النبي صمويل', 'en' => 'An-Nabi Samuel'],
                ['ar' => 'النبي يعقوب', 'en' => "An-Nabi Ya'qub"],
                ['ar' => 'ام طوبا', 'en' => 'Umm Tuba'],
                ['ar' => 'امليسون', 'en' => 'Um Lison'],
                ['ar' => 'ام ليسون', 'en' => 'Um Lison'],
                ['ar' => 'باب الاسباط', 'en' => "Lions' Gate"],
                ['ar' => 'باب الجنائز', 'en' => "Bab al-Jana'iz (Funeral Gate)"],
                ['ar' => 'باب الحديد', 'en' => 'Iron Gate'],
                ['ar' => 'باب الخليل', 'en' => 'Jaffa Gate (Bab al-Khalil)'],
                ['ar' => 'باب الرحمة', 'en' => 'Gate of Mercy'],
                ['ar' => 'باب الزاهرة', 'en' => "Bab az-Zahra (Herod's Gate)"],
                ['ar' => 'باب الساهرة', 'en' => "Bab as-Sahira (Herod's Gate)"],
                ['ar' => 'باب العامود', 'en' => 'Damascus Gate'],
                ['ar' => 'باب القطامين', 'en' => 'Bab al-Qatamin'],
                ['ar' => 'باب المثلث', 'en' => 'Triangle Gate'],
                ['ar' => 'باب المزدوج', 'en' => 'Double Gate'],
                ['ar' => 'باب المطهرة', 'en' => 'Ablution Gate'],
                ['ar' => 'باب المغاربة', 'en' => 'Mughrabi Gate'],
                ['ar' => 'باب الناظر', 'en' => 'Inspector Gate (Bab an-Nazir)'],
                ['ar' => 'باب الواحد', 'en' => 'Al-Wahid Gate'],
                ['ar' => 'باب حطة', 'en' => 'Hitta Gate'],
                ['ar' => 'بسجات زئيف', 'en' => "Pisgat Ze'ev"],
                ['ar' => 'بيت حنينا (قدس)', 'en' => 'Beit Hanina (Jerusalem)'],
                ['ar' => 'بيت صفافا', 'en' => 'Beit Safafa'],
                ['ar' => 'تل بيوت', 'en' => 'Talpiot'],
                ['ar' => 'جبل الزيتون', 'en' => 'Mount of Olives'],
                ['ar' => 'جبل المشارف', 'en' => 'Mount Scopus'],
                ['ar' => 'جبل المكبر', 'en' => 'Jabal al-Mukaber'],
                ['ar' => 'جبل صهيون', 'en' => 'Mount Zion'],
                ['ar' => 'جفعات زئيف', 'en' => "Giv'at Ze'ev"],
                ['ar' => 'جفعات شاؤل', 'en' => "Giv'at Shaul"],
                ['ar' => 'جفعات شموئيل', 'en' => "Giv'at Shmuel"],
                ['ar' => 'جنة عدن', 'en' => 'Garden of Eden'],
                ['ar' => 'جيلو', 'en' => 'Gilo'],
                ['ar' => 'حارة النصارى', 'en' => 'Christian Quarter'],
                ['ar' => 'حي البستان', 'en' => 'Al-Bustan Neighborhood'],
                ['ar' => 'دوار النخيل', 'en' => 'Palm Roundabout'],
                ['ar' => 'دوار بطن الهوا', 'en' => 'Batn al-Hawa Roundabout'],
                ['ar' => 'راس العامود', 'en' => 'Ras al-Amud'],
                ['ar' => 'سلوان', 'en' => 'Silwan'],
                ['ar' => 'شارع الزهراء', 'en' => 'Az-Zahra Street'],
                ['ar' => 'شارع السلطان سليمان', 'en' => 'Sultan Suleiman Street'],
                ['ar' => 'شارع صلاح الدين', 'en' => "Salah ad-Din Street"],
                ['ar' => 'شارع يافا', 'en' => 'Jaffa Street'],
                ['ar' => 'شرفات', 'en' => 'Sharafat'],
                ['ar' => 'شعفاط', 'en' => "Shu'afat"],
                ['ar' => 'شعفاط الابراج', 'en' => "Shu'afat - Towers"],
                ['ar' => 'شيخ سعد القدس', 'en' => 'Sheikh Saad - Jerusalem'],
                ['ar' => 'صور باهر', 'en' => 'Sur Baher'],
                ['ar' => 'عطروت', 'en' => 'Atarot'],
                ['ar' => 'عين اللوزة', 'en' => 'Ein al-Louzeh'],
                ['ar' => 'عين كارم', 'en' => 'Ein Karem'],
                ['ar' => 'كريات مناحيم', 'en' => 'Kiryat Menachem'],
                ['ar' => 'كريات يوفيل', 'en' => 'Kiryat Yovel'],
                ['ar' => 'محنة يودا', 'en' => 'Mahane Yehuda'],
                ['ar' => 'نزلة حزما القدس', 'en' => 'Nazlat Hizma - Jerusalem'],
                ['ar' => 'هداسا العيساوية', 'en' => "Hadassah - Al-'Isawiya"],
                ['ar' => 'واد الحمص', 'en' => 'Wadi al-Hummus'],
                ['ar' => 'واد قدوم', 'en' => 'Wadi Qudum'],
                ['ar' => 'وادي الجوز', 'en' => 'Wadi al-Joz'],
                ['ar' => 'وادي الدم', 'en' => 'Wadi ad-Dam'],
                ['ar' => 'وادي الربابة', 'en' => 'Wadi ar-Rababa'],
                ['ar' => 'وادي حلوة', 'en' => 'Wadi Hilweh'],
            ],
            // المثلث
            'المثلث' => [
                ['ar' => 'البطيمات', 'en' => 'Al-Bateimat'],
                ['ar' => 'الطيبة', 'en' => 'Tayibe'],
                ['ar' => 'الطيرة', 'en' => 'At-Tira'],
                ['ar' => 'ام الفحم', 'en' => 'Umm al-Fahm'],
                ['ar' => 'ام القطف', 'en' => 'Umm al-Qutuf'],
                ['ar' => 'باقة الغربية', 'en' => 'Baqa al-Gharbiyye'],
                ['ar' => 'برطعة (الداخل)', 'en' => "Barta'a (Interior)"],
                ['ar' => 'بياضة', 'en' => 'Bayada'],
                ['ar' => 'جت المثلث', 'en' => 'Jatt (Triangle)'],
                ['ar' => 'جلجوليا', 'en' => 'Jaljulia'],
                ['ar' => 'حريش', 'en' => 'Harish'],
                ['ar' => 'راس العين', 'en' => "Ras al-'Ain"],
                ['ar' => 'زلفة', 'en' => 'Zalfa'],
                ['ar' => 'زيمر', 'en' => 'Zemer'],
                ['ar' => 'سالم', 'en' => 'Salem'],
                ['ar' => 'عارة', 'en' => "'Ara"],
                ['ar' => 'عرعرة', 'en' => "Ar'ara"],
                ['ar' => 'عين ابراهيم', 'en' => "Ein Ibrahim"],
                ['ar' => 'عين السهلة', 'en' => 'Ein as-Sahla'],
                ['ar' => 'عين جرار', 'en' => 'Ein Jarar'],
                ['ar' => 'قلنسوه', 'en' => 'Qalansuwa'],
                ['ar' => 'كفر برا', 'en' => 'Kafr Bara'],
                ['ar' => 'كفر قاسم', 'en' => 'Kafr Qasim'],
                ['ar' => 'كفر قرع', 'en' => 'Kafr Qara'],
                ['ar' => 'مشيرفة', 'en' => 'Misherife'],
                ['ar' => 'مصمص', 'en' => 'Musmus'],
                ['ar' => 'معاوية', 'en' => "Mu'awiya"],
                ['ar' => 'ميسر', 'en' => 'Meiser'],
            ],
            // المركز
            'المركز' => [
                ['ar' => 'الرملة', 'en' => 'Ramla'],
                ['ar' => 'اللد', 'en' => 'Lod'],
                ['ar' => 'اللطرون', 'en' => 'Latrun'],
                ['ar' => 'بات يام', 'en' => 'Bat Yam'],
                ['ar' => 'بتساريم', 'en' => 'Bezarim'],
                ['ar' => 'بني براك', 'en' => 'Bnei Brak'],
                ['ar' => 'بئر يعقوب', 'en' => 'Be’er Ya’akov'],
                ['ar' => 'بيتح تكفا', 'en' => 'Petah Tikva'],
                ['ar' => 'بيت حنان', 'en' => 'Beit Hanan'],
                ['ar' => 'بيت شيمش', 'en' => 'Beit Shemesh'],
                ['ar' => 'بيت عزرا', 'en' => 'Beit Ezra'],
                ['ar' => 'تل ابيب', 'en' => 'Tel Aviv'],
                ['ar' => 'جفعات شمؤويل', 'en' => 'Givat Shmuel'],
                ['ar' => 'جفعتايم', 'en' => "Giv'atayim"],
                ['ar' => 'جني هتكفا', 'en' => 'Ganei Hatikva'],
                ['ar' => 'حولون', 'en' => 'Holon'],
                ['ar' => 'راحوبوت', 'en' => 'Rehovot'],
                ['ar' => 'رامات جام', 'en' => 'Ramat Gan'],
                ['ar' => 'رعنانا', 'en' => "Ra'anana"],
                ['ar' => 'رمات جان', 'en' => 'Ramat Gan'],
                ['ar' => 'ريشون ليتسيون', 'en' => 'Rishon LeZion'],
                ['ar' => 'كريات اونو', 'en' => 'Kiryat Ono'],
                ['ar' => 'كفار حبد', 'en' => 'Kfar Chabad'],
                ['ar' => 'كفار سابا', 'en' => 'Kfar Saba'],
                ['ar' => 'مودعين', 'en' => 'Modiin'],
                ['ar' => 'نتانيا', 'en' => 'Netanya'],
                ['ar' => 'نس تسيون', 'en' => 'Ness Ziona'],
                ['ar' => 'هرتسيليا', 'en' => 'Herzliya'],
                ['ar' => 'هودا شارون', 'en' => 'Hod HaSharon'],
                ['ar' => 'يافا', 'en' => 'Jaffa'],
                ['ar' => 'يهود', 'en' => 'Yehud'],
            ],
            // بئر السبع
            'بئر السبع' => [
                ['ar' => 'أبو تلول', 'en' => 'Abu Talul'],
                ['ar' => 'أبو قرينات', 'en' => 'Abu Qrenat'],
                ['ar' => 'ابو قويدر', 'en' => 'Abu Quweider'],
                ['ar' => 'اشدود', 'en' => 'Ashdod'],
                ['ar' => 'الباط', 'en' => 'Al-Bat'],
                ['ar' => 'الباطل', 'en' => 'Al-Batil'],
                ['ar' => 'البحيرة', 'en' => 'Al-Buhaira (The Lake)'],
                ['ar' => 'البقار', 'en' => 'Al-Baqar'],
                ['ar' => 'الحمرة', 'en' => 'Al-Hamra'],
                ['ar' => 'الحويطات', 'en' => 'Al-Huwaytat'],
                ['ar' => 'الزرنوق', 'en' => 'Az-Zarnuq'],
                ['ar' => 'الزعرورة', 'en' => "Az-Za'rura"],
                ['ar' => 'السدير', 'en' => 'As-Sidir'],
                ['ar' => 'السرة', 'en' => 'As-Sarra'],
                ['ar' => 'السيد', 'en' => 'As-Sayyid'],
                ['ar' => 'العزازمة', 'en' => "Al-'Azazma"],
                ['ar' => 'الغراء', 'en' => 'Al-Ghara'],
                ['ar' => 'الغرة', 'en' => 'Al-Ghura'],
                ['ar' => 'الفرعة', 'en' => "Al-Far'a"],
                ['ar' => 'القطامات', 'en' => 'Al-Qatamat'],
                ['ar' => 'اللقية', 'en' => 'Al-Laqiya'],
                ['ar' => 'المذبح', 'en' => 'Al-Madhbah'],
                ['ar' => 'المساعديه', 'en' => 'Al-Musa’idiyya'],
                ['ar' => 'المطهر', 'en' => 'Al-Mutahhar'],
                ['ar' => 'المكيمن', 'en' => 'Al-Makiman'],
                ['ar' => 'أم بطين', 'en' => 'Umm Batin'],
                ['ar' => 'ام رتام', 'en' => 'Umm Ratam'],
                ['ar' => 'ام نميله', 'en' => 'Umm Namila'],
                ['ar' => 'اوفكيم', 'en' => 'Ofakim'],
                ['ar' => 'باط الصرايعه', 'en' => "Bat as-Saray'a"],
                ['ar' => 'بير الحمام', 'en' => 'Bir al-Hamam'],
                ['ar' => 'بير المشاش', 'en' => 'Bir al-Mshash'],
                ['ar' => 'بير هداج', 'en' => 'Bir Hadaj'],
                ['ar' => 'ترابين', 'en' => 'Tarabin'],
                ['ar' => 'ترابين الصانع', 'en' => "Tarabin as-Sana'"],
                ['ar' => 'تل السبع', 'en' => "Tel as-Sabi' (Tel Sheva)"],
                ['ar' => 'تل الملح', 'en' => 'Tel al-Milh'],
                ['ar' => 'تل عراد', 'en' => 'Tel Arad'],
                ['ar' => 'حورة', 'en' => 'Hura'],
                ['ar' => 'خربه الوطن', 'en' => 'Khirbet al-Watan'],
                ['ar' => 'خربه زباله', 'en' => 'Khirbet Zbala'],
                ['ar' => 'خشم زنه', 'en' => 'Khashm Zanna'],
                ['ar' => 'دريجات', 'en' => 'Dreijat'],
                ['ar' => 'ديمونا', 'en' => 'Dimona'],
                ['ar' => 'رخمة', 'en' => 'Rakhma'],
                ['ar' => 'رموت حوفاف', 'en' => 'Ramat Hovav'],
                ['ar' => 'رهط', 'en' => 'Rahat'],
                ['ar' => 'سديروت', 'en' => 'Sderot'],
                ['ar' => 'سعوه', 'en' => "Sa'wa"],
                ['ar' => 'شقيب السلام', 'en' => 'Shaqib al-Salam (Segev Shalom)'],
                ['ar' => 'صواوين', 'en' => 'Sawaween'],
                ['ar' => 'طويل أبو جرول', 'en' => "Tuwayl Abu Jarwal"],
                ['ar' => 'ظحي', 'en' => 'Dhahi'],
                ['ar' => 'عبدة', 'en' => 'Abda'],
                ['ar' => 'عرعره النقب', 'en' => "Ar'ara an-Naqab"],
                ['ar' => 'عسقلان', 'en' => 'Ashkelon'],
                ['ar' => 'عمرة', 'en' => 'Amra'],
                ['ar' => 'عوجان', 'en' => "'Awjan"],
                ['ar' => 'قصر السر', 'en' => 'Qasr as-Sir'],
                ['ar' => 'كحله', 'en' => 'Kuhla'],
                ['ar' => 'كريات جات', 'en' => 'Kiryat Gat'],
                ['ar' => 'كريات ملاخي', 'en' => 'Kiryat Malachi'],
                ['ar' => 'كسيفة', 'en' => 'Kuseife'],
                ['ar' => 'مدينة بئر السبع', 'en' => 'Beersheba City'],
                ['ar' => 'مكحول', 'en' => 'Makhul'],
                ['ar' => 'مولاده', 'en' => 'Molada'],
                ['ar' => 'نتيفوت', 'en' => 'Netivot'],
                ['ar' => 'نفحه', 'en' => 'Nafha'],
                ['ar' => 'وادي أريحا', 'en' => 'Wadi Ariha'],
                ['ar' => 'وادي المشاش', 'en' => 'Wadi al-Mshash'],
                ['ar' => 'وادي النعم', 'en' => "Wadi an-Na'am"],
            ],
            // بيت لحم
            'بيت لحم' => [
                ['ar' => 'الجبعة', 'en' => "Al-Jaba'"],
                ['ar' => 'الحلقوم', 'en' => 'Al-Halqoom'],
                ['ar' => 'الخاص', 'en' => 'Al-Khas'],
                ['ar' => 'الشواورة', 'en' => 'Ash-Shawawra'],
                ['ar' => 'العبيدية', 'en' => "Al-'Ubeidiya"],
                ['ar' => 'العساكرة', 'en' => "Al-'Asakira"],
                ['ar' => 'الفريديس', 'en' => 'Al-Fureidis'],
                ['ar' => 'المدبسة', 'en' => 'Al-Madbasa'],
                ['ar' => 'المعصرة', 'en' => "Al-Ma'sara"],
                ['ar' => 'المنشية', 'en' => 'Al-Manshiya'],
                ['ar' => 'المنيا', 'en' => 'Al-Minya'],
                ['ar' => 'الولجة', 'en' => 'Al-Walaja'],
                ['ar' => 'ام سلمونة', 'en' => 'Um Salamuna'],
                ['ar' => 'بتير', 'en' => 'Battir'],
                ['ar' => 'بيت تعمر', 'en' => "Bayt Ta'mar"],
                ['ar' => 'بيت فجار', 'en' => 'Beit Fajjar'],
                ['ar' => 'بيت لحم', 'en' => 'Bethlehem'],
                ['ar' => 'تقوع', 'en' => "Tuqu'"],
                ['ar' => 'جب الذيب', 'en' => 'Jubb adh-Dhib'],
                ['ar' => 'جناتا', 'en' => 'Janata'],
                ['ar' => 'جورة الشمعة', 'en' => "Jurat ash-Shama'a"],
                ['ar' => 'حوسان', 'en' => 'Husan'],
                ['ar' => 'خربة تقوع', 'en' => "Khirbet Tuqu'"],
                ['ar' => 'خلة الحداد', 'en' => 'Khillet al-Haddad'],
                ['ar' => 'خلة اللوزة', 'en' => 'Khillet al-Lawza'],
                ['ar' => 'خلة النعمان', 'en' => "Khirbet an-Nu'man"],
                ['ar' => 'خلة حمامة', 'en' => 'Khillet Hamama'],
                ['ar' => 'خلة سكاريا', 'en' => 'Khillet Skaria'],
                ['ar' => 'دار صلاح', 'en' => 'Dar Salah'],
                ['ar' => 'زعترة', 'en' => "Za'tara"],
                ['ar' => 'عرب الرشايدة', 'en' => 'Arab ar-Rashayda'],
                ['ar' => 'كيسان', 'en' => 'Kisan'],
                ['ar' => 'مدينة بيت لحم−شارع الكركفة', 'en' => 'Bethlehem City - Al-Karkafa Street'],
                ['ar' => 'مراح رباح', 'en' => 'Marah Rabah'],
                ['ar' => 'مراح معلا', 'en' => "Marah Ma'la"],
                ['ar' => 'نحالين', 'en' => 'Nahalin'],
                ['ar' => 'هندازة وبريضعة', 'en' => "Hindaza and Bariz'a"],
                ['ar' => 'وادي النيص', 'en' => 'Wadi an-Nis'],
                ['ar' => 'وادي امحيميد', 'en' => 'Wadi Imhimeid'],
                ['ar' => 'وادي رحال', 'en' => 'Wadi Rahhal'],
                ['ar' => 'وادي فوكين', 'en' => 'Wadi Fukin'],
                // إضافات قرى وأحياء بيت لحم
                ['ar' => 'ارطاس', 'en' => 'Artas'],
                ['ar' => 'الخضر', 'en' => 'Al-Khader'],
                ['ar' => 'الدوحة', 'en' => 'Ad-Duha'],
                ['ar' => 'بئر عونة', 'en' => "Bir 'Una"],
                ['ar' => 'بيت جالا', 'en' => 'Beit Jala'],
                ['ar' => 'بيت ساحور', 'en' => 'Beit Sahour'],
                ['ar' => 'شارع القدس الخليل', 'en' => 'Jerusalem-Hebron Street'],
                ['ar' => 'مخيم الدهيشة', 'en' => 'Dheisheh Camp'],
                ['ar' => 'مخيم العزة', 'en' => 'Al-Azza Camp'],
                ['ar' => 'مخيم عايدة', 'en' => 'Aida Camp'],
                ['ar' => 'مدينة بيت لحم', 'en' => 'Bethlehem City'],
                ['ar' => 'مدينة بيت لحم−دوار ارارات', 'en' => 'Bethlehem City - Ararat Roundabout'],
                ['ar' => 'مدينة بيت لحم−شارع الجبل', 'en' => 'Bethlehem City - Jabal Street'],
                ['ar' => 'مدينة بيت لحم−شارع المهد', 'en' => 'Bethlehem City - Nativity Street'],
                ['ar' => 'واد شاهين', 'en' => 'Wad Shahin'],
                ['ar' => 'واد معالي', 'en' => "Wad Ma'ali"],
                ['ar' => 'واد معالي−شارع الصف', 'en' => "Wad Ma'ali - As-Saf Street"],
                ['ar' => 'وسط البلد', 'en' => 'Downtown'],
            ],
            // جنين
            'جنين' => [
                ['ar' => 'الجديدة', 'en' => 'Al-Judeida'],
                ['ar' => 'الجلمة', 'en' => 'Al-Jalameh'],
                ['ar' => 'الحارة الشرقية', 'en' => 'Eastern Neighborhood'],
                ['ar' => 'الخلجان', 'en' => 'Al-Khiljan'],
                ['ar' => 'الرامة', 'en' => 'Ar-Rama'],
                ['ar' => 'الزاوية', 'en' => 'Az-Zawiya'],
                ['ar' => 'الزبابدة', 'en' => 'Az-Zababdeh'],
                ['ar' => 'الشهداء', 'en' => 'Ash-Shuhada'],
                ['ar' => 'الضمايرة', 'en' => 'Ad-Dumayra'],
                ['ar' => 'الطرم', 'en' => 'At-Tarm'],
                ['ar' => 'الطيبة', 'en' => 'At-Tayba'],
                ['ar' => 'العرقة', 'en' => "Al-'Arqa"],
                ['ar' => 'العصاعصة', 'en' => "Al-'Asa'asa"],
                ['ar' => 'العطارة', 'en' => "Al-'Attara"],
                ['ar' => 'الفندقومية', 'en' => 'Al-Funduqumiya'],
                ['ar' => 'المطلة', 'en' => 'Al-Mutalla'],
                ['ar' => 'المغير', 'en' => 'Al-Mughayir'],
                ['ar' => 'المنصورة', 'en' => 'Al-Mansura'],
                ['ar' => 'الهاشمية', 'en' => 'Al-Hashimiya'],
                ['ar' => 'اليامون', 'en' => 'Al-Yamun'],
                ['ar' => 'أم التوت', 'en' => 'Umm at-Tut'],
                ['ar' => 'أم الريحان', 'en' => 'Umm ar-Rihan'],
                ['ar' => 'أم دار', 'en' => 'Umm Dar'],
                ['ar' => 'إمريحة', 'en' => 'Imreiha'],
                ['ar' => 'برقين', 'en' => 'Burqin'],
                ['ar' => 'بيت قاد (الجنوبي)', 'en' => 'Beit Qad (South)'],
                ['ar' => 'بير الباشا', 'en' => "Bir al-Basha"],
                ['ar' => 'تعنك', 'en' => "Ti'innik"],
                ['ar' => 'تنين', 'en' => 'Tannin'],
                ['ar' => 'جبع', 'en' => "Jaba'"],
                ['ar' => 'جلبون', 'en' => 'Jalbun'],
                ['ar' => 'جلقموس', 'en' => 'Jalqamus'],
                ['ar' => 'جنين', 'en' => 'Jenin'],
                ['ar' => 'جنين - حي الزهراء', 'en' => 'Jenin - Al-Zahra Neighborhood'],
                ['ar' => 'خربة عبد الله اليونس', 'en' => "Khirbet 'Abdallah al-Younis"],
                ['ar' => 'دير ابو ضعيف', 'en' => "Deir Abu Da'if"],
                ['ar' => 'دير غزالة', 'en' => 'Deir Ghazala'],
                ['ar' => 'رابا', 'en' => 'Raba'],
                ['ar' => 'رمانة', 'en' => 'Rummana'],
                ['ar' => 'زبدة', 'en' => 'Zubda'],
                ['ar' => 'زبوبا', 'en' => 'Zububa'],
                ['ar' => 'سيريس', 'en' => 'Siris'],
                ['ar' => 'سيلة الحارثية', 'en' => 'Silat al-Harithiya'],
                ['ar' => 'سيلة الظهر', 'en' => 'Silat adh-Dhahr'],
                ['ar' => 'صانور', 'en' => 'Sanur'],
                ['ar' => 'صير', 'en' => 'Sir'],
                ['ar' => 'طورة الشرقية', 'en' => 'Tura ash-Sharqiya'],
                ['ar' => 'طورة الغربية', 'en' => 'Tura al-Gharbiya'],
                ['ar' => 'ظهر العبد', 'en' => "Dhaher al-'Abed"],
                ['ar' => 'ظهر المالح', 'en' => 'Dhaher al-Maleh'],
                ['ar' => 'عابا (الغربية)', 'en' => "A'aba (West)"],
                ['ar' => 'عانين', 'en' => "'Anin"],
                ['ar' => 'عجة', 'en' => "'Ajja"],
                ['ar' => 'عرابة', 'en' => 'Arraba'],
                ['ar' => 'عرانة', 'en' => "'Arana"],
                ['ar' => 'عربونة', 'en' => 'Arbuna'],
                ['ar' => 'عنزة', 'en' => "'Anzah"],
                ['ar' => 'فحمة', 'en' => 'Fahma'],
                ['ar' => 'فحمة الجديدة', 'en' => 'New Fahma'],
                ['ar' => 'فقوعة', 'en' => "Faqqu'a"],
                ['ar' => 'قباطية', 'en' => 'Qabatiya'],
                ['ar' => 'كفر دان', 'en' => 'Kafr Dan'],
                ['ar' => 'كفر راعي', 'en' => "Kafr Ra'i"],
                ['ar' => 'كفر قود', 'en' => 'Kafr Qud'],
                ['ar' => 'كفير', 'en' => 'Al-Kfayr'],
                ['ar' => 'كفيرت', 'en' => 'Kifiret'],
                ['ar' => 'مخيم جنين', 'en' => 'Jenin Camp'],
                ['ar' => 'مدينة جنين', 'en' => 'Jenin City'],
                ['ar' => 'مدينة جنين−الجابريات', 'en' => 'Jenin City - Al-Jabariyat'],
                ['ar' => 'مدينة جنين−الجامعة الامريكية-جنين', 'en' => 'Jenin City - Arab American University'],
                ['ar' => 'مدينة جنين−الحي الشرقي', 'en' => 'Jenin City - Eastern Neighborhood'],
                ['ar' => 'مدينة جنين−الحي الغربي', 'en' => 'Jenin City - Western Neighborhood'],
                ['ar' => 'مدينة جنين−السويطات', 'en' => 'Jenin City - Al-Suwaytat'],
                ['ar' => 'مدينة جنين−المغشية', 'en' => 'Jenin City - Al-Mughshiya'],
                ['ar' => 'مدينة جنين−المنطقة الصناعية -جنين', 'en' => 'Jenin City - Industrial Zone (Jenin)'],
                ['ar' => 'مدينة جنين−جنين البلدة القديمة', 'en' => 'Jenin City - Old City'],
                ['ar' => 'مدينة جنين−جنين - الدوار', 'en' => 'Jenin City - The Roundabout'],
                ['ar' => 'مدينة جنين−جنين-وسط البلد', 'en' => 'Jenin City - Downtown'],
                ['ar' => 'مدينة جنين−جنين-وسط البلد', 'en' => 'Jenin City - Downtown'],
                ['ar' => 'مدينة جنين−حي البساتين', 'en' => 'Jenin City - Al-Bustan Neighborhood'],
                ['ar' => 'مدينة جنين−حي الهدف', 'en' => 'Jenin City - Al-Hadaf Neighborhood'],
                ['ar' => 'مدينة جنين−خروبة', 'en' => 'Jenin City - Kharouba'],
                ['ar' => 'مدينة جنين−سهل مرج بن عامر', 'en' => 'Jenin City - Marj Ibn Amer Plain'],
                ['ar' => 'مدينة جنين−شارع أبو بكر', 'en' => 'Jenin City - Abu Bakr Street'],
                ['ar' => 'مدينة جنين−شارع الجامعة', 'en' => 'Jenin City - University Street'],
                ['ar' => 'مدينة جنين−شارع الحسبة-جنين', 'en' => 'Jenin City - Hasba Street (Jenin)'],
                ['ar' => 'مدينة جنين−شارع الملك فيصل-جنين', 'en' => 'Jenin City - King Faisal Street (Jenin)'],
                ['ar' => 'مدينة جنين−شارع الناصرة جنين', 'en' => 'Jenin City - Nazareth Street (Jenin)'],
                ['ar' => 'مدينة جنين−شارع حيفا جنين', 'en' => 'Jenin City - Haifa Street (Jenin)'],
                ['ar' => 'مدينة جنين−شارع نابلس جنين', 'en' => 'Jenin City - Nablus Street (Jenin)'],
                ['ar' => 'مدينة جنين−شارع يحيى عياش', 'en' => 'Jenin City - Yahya Ayyash Street'],
                ['ar' => 'مدينة جنين−ضاحية الجنان', 'en' => 'Jenin City - Al-Jinan Suburb'],
                ['ar' => 'مدينة جنين−ضاحية الزيتونة', 'en' => 'Jenin City - Al-Zeitouna Suburb'],
                ['ar' => 'مدينة جنين−كفريات', 'en' => 'Jenin City - Kafriyat'],
                ['ar' => 'مركة', 'en' => 'Marka'],
                ['ar' => 'مسلية', 'en' => 'Misilya'],
                ['ar' => 'مشروع بيت قاد (الشمالي)', 'en' => 'Beit Qad Project (North)'],
                ['ar' => 'ميثلون', 'en' => 'Mithlon'],
                ['ar' => 'نزلة الشيخ زيد', 'en' => 'Nazlet Sheikh Zaid'],
                ['ar' => 'وادي الضبع', 'en' => "Wadi ad-Dub'a"],
                ['ar' => 'وادي دعوق', 'en' => "Wadi Da'uq"],
                ['ar' => 'يعبد', 'en' => "Ya'bad"],
            ],
            // رام الله والبيرة
            'رام الله والبيرة' => [
                ['ar' => 'أبو شخيدم', 'en' => 'Abu Shkheidem'],
                ['ar' => 'أبو قش', 'en' => 'Abu Qash'],
                ['ar' => 'اسكان الشرطة', 'en' => 'Police Housing'],
                ['ar' => 'الجانية', 'en' => 'Al-Janiya'],
                ['ar' => 'الجديرة', 'en' => 'Al-Judeira'],
                ['ar' => 'الجيب', 'en' => 'Al-Jib'],
                ['ar' => 'الحي الدبلوماسي', 'en' => 'Diplomatic Quarter'],
                ['ar' => 'الطيبة', 'en' => 'At-Tayba'],
                ['ar' => 'القبيبة', 'en' => 'Al-Qubeiba'],
                ['ar' => 'اللبن الغربي', 'en' => 'Al-Lubban al-Gharbi'],
                ['ar' => 'المدية', 'en' => 'Al-Midya'],
                ['ar' => 'المزرعة الشرقية', 'en' => 'Al-Mazra\'a ash-Sharqiya'],
                ['ar' => 'المزرعة الغربية', 'en' => 'Al-Mazra\'a al-Gharbiya'],
                ['ar' => 'المغير', 'en' => 'Al-Mughayir'],
                ['ar' => 'النبي صالح', 'en' => 'An-Nabi Salih'],
                ['ar' => 'أم صفا', 'en' => 'Um Safa'],
                ['ar' => 'بدرس', 'en' => 'Badrus'],
                ['ar' => 'بدو', 'en' => 'Biddu'],
                ['ar' => 'برقة', 'en' => 'Burqa'],
                ['ar' => 'برهام', 'en' => 'Birham'],
                ['ar' => 'بلعين', 'en' => "Bil'in"],
                ['ar' => 'بيت اجزا', 'en' => 'Bayt Ijza'],
                ['ar' => 'بيت اكسا', 'en' => 'Beit Iksa'],
                ['ar' => 'بيت حنينا - ضفة', 'en' => 'Beit Hanina - West Bank'],
                ['ar' => 'بيت دقو', 'en' => 'Beit Duqqu'],
                ['ar' => 'بيت ريما', 'en' => 'Bayt Rima'],
                ['ar' => 'بيت سوريك', 'en' => 'Beit Surik'],
                ['ar' => 'بيت سيرا', 'en' => 'Beit Sira'],
                ['ar' => 'بيت عنان', 'en' => 'Beit Anan'],
                ['ar' => 'بيت عور التحتا', 'en' => "Beit 'Ur at-Tahta"],
                ['ar' => 'بيت عور الفوقا', 'en' => "Beit 'Ur al-Fauqa"],
                ['ar' => 'بيت لقيا', 'en' => 'Beit Liqya'],
                ['ar' => 'بيتللو', 'en' => 'Beitillu'],
                ['ar' => 'بيتين', 'en' => 'Beitin'],
                ['ar' => 'بيرزيت', 'en' => 'Birzeit'],
                ['ar' => 'بير نبالا', 'en' => 'Bir Nabala'],
                ['ar' => 'ترمسعيا', 'en' => "Turmus'ayya"],
                ['ar' => 'جفنا', 'en' => 'Jifna'],
                ['ar' => 'جلجيليا', 'en' => 'Jaljiliya'],
                ['ar' => 'جمالة', 'en' => 'Jamala'],
                ['ar' => 'جيبيا', 'en' => 'Jibiya'],
                ['ar' => 'خربة أبو فلاح', 'en' => 'Khirbet Abu Falah'],
                ['ar' => 'خربثا المصباح', 'en' => 'Khirbet al-Misbah'],
                ['ar' => 'خربثا بني حارث', 'en' => 'Khirbet Bani Harith'],
                ['ar' => 'دورا القرع', 'en' => "Dura al-Qar'"],
                ['ar' => 'دير ابزيع', 'en' => "Deir Ibzi'"],
                ['ar' => 'دير أبو مشعل', 'en' => "Deir Abu Mash'al"],
                ['ar' => 'دير السودان', 'en' => 'Deir as-Sudan'],
                ['ar' => 'دير جرير', 'en' => 'Deir Jarir'],
                ['ar' => 'دير دبوان', 'en' => 'Deir Dibwan'],
                ['ar' => 'دير عمار', 'en' => 'Deir Ammar'],
                ['ar' => 'دير غسانة', 'en' => 'Deir Ghassana'],
                ['ar' => 'دير قديس', 'en' => 'Deir Qaddis'],
                ['ar' => 'دير نظام', 'en' => 'Deir Nizam'],
                ['ar' => 'راس كركر', 'en' => 'Ras Karkar'],
                ['ar' => 'رافات', 'en' => 'Rafat'],
                ['ar' => 'رام الله والبيرة', 'en' => 'Ramallah and Al-Bireh'],
                ['ar' => 'رمون', 'en' => 'Rummon'],
                ['ar' => 'رنتيس', 'en' => 'Rantis'],
                ['ar' => 'روابي', 'en' => 'Rawabi'],
                ['ar' => 'سردا', 'en' => 'Sarda'],
                ['ar' => 'سلواد', 'en' => 'Silwad'],
                ['ar' => 'سنجل', 'en' => 'Sinjil'],
                ['ar' => 'شبتين', 'en' => 'Shabtin'],
                ['ar' => 'شقبا', 'en' => 'Shuqba'],
                ['ar' => 'صفا', 'en' => 'Saffa'],
                ['ar' => 'ضاحية الاتحاد', 'en' => 'Dahiyat al-Ittihad'],
                ['ar' => 'ضاحية التربية والتعليم', 'en' => 'Education Suburb'],
                ['ar' => 'ضاحية الريحان', 'en' => 'Al-Reihan Suburb'],
                ['ar' => 'ضاحية السنديان', 'en' => 'Al-Sindiyan Suburb'],
                ['ar' => 'ضاحية الغدير', 'en' => 'Al-Ghadeer Suburb'],
                ['ar' => 'ضاحية النجمة', 'en' => 'An-Najma Suburb'],
                ['ar' => 'عابود', 'en' => "'Abud"],
                ['ar' => 'عارورة', 'en' => "'Arura"],
                ['ar' => 'عبوين', 'en' => "'Abwein"],
                ['ar' => 'عجول', 'en' => "'Ajjul"],
                ['ar' => 'عطارة', 'en' => "'Atara"],
                ['ar' => 'عين سينيا', 'en' => "'Ain Sinya"],
                ['ar' => 'عين عريك', 'en' => "'Ain 'Arik"],
                ['ar' => 'عين قينيا', 'en' => "'Ain Qiniya"],
                ['ar' => 'عين يبرود', 'en' => "'Ain Yabrud"],
                ['ar' => 'قبيا', 'en' => 'Qibiya'],
                ['ar' => 'قراوة بني زيد', 'en' => 'Qarawat Bani Zaid'],
                ['ar' => 'قرية الطيرة', 'en' => 'At-Tira Village'],
                ['ar' => 'قطنة', 'en' => 'Qatanna'],
                ['ar' => 'قلنديا البلد', 'en' => 'Qalandiya al-Balad'],
                ['ar' => 'كفر عين', 'en' => "Kafr 'Ain"],
                ['ar' => 'كفر مالك', 'en' => 'Kafr Malik'],
                ['ar' => 'كفر نعمة', 'en' => "Kafr Ni'ma"],
                ['ar' => 'كوبر', 'en' => 'Kobar'],
                ['ar' => 'مخيم الجلزون', 'en' => 'Al-Jalazone Camp'],
                ['ar' => 'مزارع النوباني', 'en' => "Mazari' an-Nubani"],
                ['ar' => 'نعلين', 'en' => "Ni'lin"],
                ['ar' => 'يبرود', 'en' => 'Yabrud'],
                // إضافات أحياء رام الله والبيرة
                ['ar' => 'رام الله والبيرة - البيرة', 'en' => 'Ramallah and Al-Bireh - Al-Bireh'],
                ['ar' => 'رام الله والبيرة - مدينة رام الله', 'en' => 'Ramallah and Al-Bireh - Ramallah City'],
                ['ar' => 'مدينة رام الله−الارسال', 'en' => 'Ramallah City - Al-Irsal'],
                ['ar' => 'مدينة رام الله−الشرفة', 'en' => 'Ramallah City - Al-Shurfa'],
                ['ar' => 'مدينة رام الله−الصناعية البيرة', 'en' => 'Ramallah City - Al-Bireh Industrial Area'],
                ['ar' => 'مدينة رام الله−الصناعية بيتونيا', 'en' => 'Ramallah City - Beitunia Industrial Area'],
                ['ar' => 'مدينة رام الله−الطيرة', 'en' => 'Ramallah City - Al-Tireh'],
                ['ar' => 'مدينة رام الله−الماصيون', 'en' => 'Ramallah City - Al-Masyoun'],
                ['ar' => 'مدينة رام الله−المصايف', 'en' => 'Ramallah City - Al-Masayif'],
                ['ar' => 'مدينة رام الله−ام الشرايط', 'en' => 'Ramallah City - Um al-Sharayit'],
                ['ar' => 'مدينة رام الله−بالوع البيرة', 'en' => "Ramallah City - Al-Balu'a (Al-Bireh)"],
                ['ar' => 'مدينة رام الله−بالوع بيتونيا', 'en' => "Ramallah City - Al-Balu'a (Beitunia)"],
                ['ar' => 'مدينة رام الله−بطن الهوى', 'en' => 'Ramallah City - Batn al-Hawa'],
                ['ar' => 'مدينة رام الله−بيتونيا', 'en' => 'Ramallah City - Beitunia'],
                ['ar' => 'مدينة رام الله−بيتونيا الخبطة', 'en' => 'Ramallah City - Beitunia Al-Khbata'],
                ['ar' => 'مدينة رام الله−بيتونيا راس يعقوب', 'en' => "Ramallah City - Beitunia Ras Ya'qub"],
                ['ar' => 'مدينة رام الله−حي الجنان', 'en' => 'Ramallah City - Al-Jinan Neighborhood'],
                ['ar' => 'مدينة رام الله−دوار الساعة', 'en' => 'Ramallah City - Clock Roundabout'],
                ['ar' => 'مدينة رام الله−رام الله التحتا', 'en' => 'Ramallah City - Lower Ramallah'],
                ['ar' => 'مدينة رام الله−رام الله دوار المنارة', 'en' => 'Ramallah City - Manara Roundabout'],
                ['ar' => 'مدينة رام الله−رام الله شارع الحسبه', 'en' => 'Ramallah City - Hasba Street'],
                ['ar' => 'مدينة رام الله-رام الله شارع القدس', 'en' => 'Ramallah City - Jerusalem Street'],
                ['ar' => 'مدينة رام الله−رام الله شارع نابلس', 'en' => 'Ramallah City - Nablus Street'],
                ['ar' => 'مدينة رام الله−رام الله وسط البلد', 'en' => 'Ramallah City - Downtown'],
                ['ar' => 'مدينة رام الله−سطح مرحبا', 'en' => 'Ramallah City - Sath Marhaba'],
                ['ar' => 'مدينة رام الله−شارع البكري', 'en' => 'Ramallah City - Al-Bakri Street'],
                ['ar' => 'مدينة رام الله−شارع المستشفى', 'en' => 'Ramallah City - Hospital Street'],
                ['ar' => 'مدينة رام الله−شارع ركب', 'en' => 'Ramallah City - Rukab Street'],
                ['ar' => 'مدينة رام الله−عين مصباح', 'en' => "Ramallah City - 'Ain Misbah"],
                ['ar' => 'مدينة رام الله−عين منجد', 'en' => "Ramallah City - 'Ain Munjid"],
                ['ar' => 'مدينة رام الله−مخيم الامعري', 'en' => "Ramallah City - Al-Am'ari Camp"],
                ['ar' => 'مدينة رام الله−مخيم قدورة', 'en' => 'Ramallah City - Qaddura Camp'],
                ['ar' => 'مدينة رام الله−مفرق 17', 'en' => 'Ramallah City - Junction 17'],
            ],
            // سلفيت
            'سلفيت' => [
                ['ar' => 'إسكاكا', 'en' => 'Iskaka'],
                ['ar' => 'بديا', 'en' => 'Biddya'],
                ['ar' => 'بروقين', 'en' => 'Bruqin'],
                ['ar' => 'حارس', 'en' => 'Haris'],
                ['ar' => 'خربة قيس', 'en' => 'Khirbet Qais'],
                ['ar' => 'دير استيا', 'en' => 'Deir Istiya'],
                ['ar' => 'دير بلوط', 'en' => 'Deir Ballut'],
                ['ar' => 'رافات', 'en' => 'Rafat'],
                ['ar' => 'سرطة', 'en' => 'Sarta'],
                ['ar' => 'سلفيت الزاوية', 'en' => 'Salfit - Az-Zawiya'],
                ['ar' => 'سلفيت وسط البلد', 'en' => 'Salfit - Downtown'],
                ['ar' => 'فرخة', 'en' => 'Farkha'],
                ['ar' => 'قراوة بني حسان', 'en' => 'Qarawat Bani Hassan'],
                ['ar' => 'قيرة', 'en' => 'Qira'],
                ['ar' => 'كفر الديك', 'en' => 'Kafr ad-Dik'],
                ['ar' => 'كفل حارس', 'en' => 'Kifl Haris'],
                ['ar' => 'مردا', 'en' => 'Marda'],
                ['ar' => 'مسحة', 'en' => 'Mas-ha'],
                ['ar' => 'ياسوف', 'en' => 'Yasuf'],
            ],
            // ضواحي القدس
            'ضواحي القدس' => [
                ['ar' => 'ابو ديس', 'en' => 'Abu Dis'],
                ['ar' => 'الخان الاحمر', 'en' => 'Khan al-Ahmar'],
                ['ar' => 'الرام', 'en' => 'Ar-Ram'],
                ['ar' => 'الزعيم', 'en' => "Az-Za'ayyem"],
                ['ar' => 'السواحرة الشرقية', 'en' => 'Ash-Shawahra ash-Sharqiya'],
                ['ar' => 'السواحرة الشرقية-الشيخ سعد (ضفة)', 'en' => 'Ash-Shawahra ash-Sharqiya - Sheikh Saad (West Bank)'],
                ['ar' => 'العيزرية', 'en' => 'Al-Eizariya'],
                ['ar' => 'جبع(الرام)', 'en' => "Jaba' (Ar-Ram)"],
                ['ar' => 'حزما', 'en' => 'Hizma'],
                ['ar' => 'سميراميس', 'en' => 'Semiramis'],
                ['ar' => 'عناتا', 'en' => 'Anata'],
                ['ar' => 'عناتا - ضاحية السلام', 'en' => 'Anata - Dahiyat as-Salam'],
                ['ar' => 'كفر عقب', 'en' => "Kafr 'Aqab"],
                ['ar' => 'مخماس', 'en' => 'Mukhmas'],
                ['ar' => 'مخيم شعفاط', 'en' => "Shu'fat Camp"],
                ['ar' => 'مخيم شعفاط−راس خميس', 'en' => "Shu'fat Camp - Ras Khamis"],
                ['ar' => 'مخيم شعفاط−راس شحادة', 'en' => "Shu'fat Camp - Ras Shihada"],
                ['ar' => 'مخيم قلنديا', 'en' => 'Qalandiya Camp'],
                ['ar' => 'نزول الكسارات', 'en' => 'Nuzul al-Kasarat'],
            ],
            // طوباس
            'طوباس' => [
                ['ar' => 'الحاوز', 'en' => 'Al-Hawoz'],
                ['ar' => 'بردلة', 'en' => 'Bardala'],
                ['ar' => 'تياسير', 'en' => 'Tayasir'],
                ['ar' => 'جباريس', 'en' => 'Jibaris'],
                ['ar' => 'حمرة', 'en' => 'Al-Hamra'],
                ['ar' => 'شارع مسجد الشهيد', 'en' => 'Martyr Mosque Street'],
                ['ar' => 'طمون', 'en' => 'Tammun'],
                ['ar' => 'طوباس وسط البلد', 'en' => 'Tubas - Downtown'],
                ['ar' => 'عقابا', 'en' => "Aqqaba"],
                ['ar' => 'عين البيضا', 'en' => 'Ein al-Beida'],
                ['ar' => 'عينون طوباس', 'en' => 'Ainun - Tubas'],
                ['ar' => 'قشدة', 'en' => 'Qashda'],
                ['ar' => 'كردلا', 'en' => 'Kardala'],
                ['ar' => 'مخيم الفارعة', 'en' => "Al-Fara'a Camp"],
                ['ar' => 'واد الفارعة', 'en' => "Wadi al-Fara'a"],
            ],
            // طولكرم
            'طولكرم' => [
                ['ar' => 'إكتابا', 'en' => 'Iktaba'],
                ['ar' => 'الجاروشية', 'en' => 'Al-Jarushiya'],
                ['ar' => 'الحارة الشرقية', 'en' => 'Eastern Neighborhood'],
                ['ar' => 'الحسبه', 'en' => 'Al-Hasba'],
                ['ar' => 'الحفاصي', 'en' => 'Al-Hafasi'],
                ['ar' => 'الراس', 'en' => 'Ar-Ras'],
                ['ar' => 'المسقوفة', 'en' => 'Al-Masqoufa'],
                ['ar' => 'النزلة الشرقية', 'en' => 'An-Nazla ash-Sharqiya'],
                ['ar' => 'النزلة الغربية', 'en' => 'An-Nazla al-Gharbiya'],
                ['ar' => 'النزلة الوسطى', 'en' => 'An-Nazla al-Wusta'],
                ['ar' => 'باقة الشرقية', 'en' => 'Baqa ash-Sharqiya'],
                ['ar' => 'بزارية', 'en' => 'Bazariya'],
                ['ar' => 'بلعا', 'en' => "Bal'a"],
                ['ar' => 'بيت ليد', 'en' => 'Bayt Lid'],
                ['ar' => 'جامعة القدس المفتوحة', 'en' => 'Al-Quds Open University'],
                ['ar' => 'حي الصوانة', 'en' => 'As-Sawwana Neighborhood'],
                ['ar' => 'خربة جبارة', 'en' => 'Khirbet Jabara'],
                ['ar' => 'دير الغصون', 'en' => 'Deir al-Ghusun'],
                ['ar' => 'ذنابة', 'en' => 'Dhannaba'],
                ['ar' => 'رامين', 'en' => 'Ramin'],
                ['ar' => 'زيتا', 'en' => 'Zeita'],
                ['ar' => 'سفارين', 'en' => 'Safarin'],
                ['ar' => 'شارع السكة', 'en' => 'Railway Street'],
                ['ar' => 'شوفة', 'en' => 'Shufa'],
                ['ar' => 'صيدا', 'en' => 'Sida'],
                ['ar' => 'طولكرم', 'en' => 'Tulkarm'],
                ['ar' => 'طولكرم−الحارة الجنوبية', 'en' => 'Tulkarm - Southern Neighborhood'],
                ['ar' => 'طولكرم−حي ارتاح', 'en' => 'Tulkarm - Irtah Neighborhood'],
                ['ar' => 'طولكرم عزبة ناصر', 'en' => "Tulkarm - 'Izbat Nasser"],
                ['ar' => 'عتيل', 'en' => "'Attil"],
                ['ar' => 'عزبة الخلال', 'en' => "'Izbat al-Khallal"],
                ['ar' => 'عزبة جراد', 'en' => "'Izbat Jarad"],
                ['ar' => 'عزبة شوفة', 'en' => "'Izbat Shufa"],
                ['ar' => 'عكابة', 'en' => 'Akkaba'],
                ['ar' => 'علار', 'en' => "'Allar"],
                ['ar' => 'عنبتا', 'en' => "'Anabta"],
                ['ar' => 'فرعون', 'en' => "Far'un"],
                ['ar' => 'قفين', 'en' => 'Qaffin'],
                ['ar' => 'كفا', 'en' => 'Kafa'],
                ['ar' => 'كفر اللبد', 'en' => 'Kafr al-Labad'],
                ['ar' => 'كفر جمال', 'en' => 'Kafr Jamal'],
                ['ar' => 'كفر رمان', 'en' => 'Kafr Rumman'],
                ['ar' => 'كفر زيباد', 'en' => 'Kafr Zibad'],
                ['ar' => 'كفر صور', 'en' => 'Kafr Sur'],
                ['ar' => 'كفر عبوش', 'en' => "Kafr 'Abbush"],
                ['ar' => 'كور', 'en' => 'Kour'],
                ['ar' => 'مخيم طولكرم', 'en' => 'Tulkarm Camp'],
                ['ar' => 'مخيم نور شمس', 'en' => 'Nur Shams Camp'],
                ['ar' => 'مدينة طولكرم', 'en' => 'Tulkarm City'],
                ['ar' => 'السوق القديم', 'en' => ' Old Market'],
                ['ar' => 'حارة السلام', 'en' => ' Al-Salam Neighborhood'],
                ['ar' => 'حارة الفقهاء', 'en' => ' Al-Fuqaha Neighborhood'],
                ['ar' => 'حي الاقصى', 'en' => ' Al-Aqsa Neighborhood'],
                ['ar' => 'حي الجنوبي', 'en' => ' Southern Neighborhood'],
                ['ar' => 'حي الشرقي', 'en' => ' Eastern Neighborhood'],
                ['ar' => 'حي الشمالي', 'en' => ' Northern Neighborhood'],
                ['ar' => 'حي الغربي', 'en' => ' Western Neighborhood'],
                ['ar' => 'دوار الساعة -طولكرم', 'en' => ' Clock Roundabout'],
                ['ar' => 'دوار جامعه الخضوري', 'en' => ' Al-Khadouri University Roundabout'],
                ['ar' => 'شارع المستشفى -طولكرم', 'en' => ' Hospital Street'],
                ['ar' => 'شارع شويكة', 'en' => ' Shweika Street'],
                ['ar' => 'شارع نابلس -طولكرم', 'en' => ' Nablus Street'],
                ['ar' => 'وسط البلد', 'en' => ' Downtown'],
                ['ar' => 'نزلة أبو النار', 'en' => "Nazlat Abu Nar"],
                ['ar' => 'نزلة عيسى', 'en' => "Nazlat 'Isa"],
            ],
            // قلقيلية
            'قلقيلية' => [
                ['ar' => 'الضبعة', 'en' => "Ad-Dab'a"],
                ['ar' => 'الفندق', 'en' => 'Al-Funduq'],
                ['ar' => 'المدور', 'en' => 'Al-Madwar'],
                ['ar' => 'النبي إلياس', 'en' => 'An-Nabi Ilyas'],
                ['ar' => 'إماتين', 'en' => 'Immatin'],
                ['ar' => 'باقة الحطب', 'en' => 'Baqat al-Hatab'],
                ['ar' => 'بيت أمين', 'en' => 'Bayt Amin'],
                ['ar' => 'جنسافوط', 'en' => 'Jinsafut'],
                ['ar' => 'جيت', 'en' => 'Jit'],
                ['ar' => 'جيوس', 'en' => 'Jayyous'],
                ['ar' => 'حبلة', 'en' => 'Habla'],
                ['ar' => 'حجة', 'en' => 'Hajja'],
                ['ar' => 'خربة صير', 'en' => 'Khirbet Sir'],
                ['ar' => 'خلة نوفل', 'en' => 'Khillet Nofal'],
                ['ar' => 'راس الطيرة', 'en' => 'Ras at-Tira'],
                ['ar' => 'راس عطية', 'en' => "Ras 'Atiya"],
                ['ar' => 'سنيريا', 'en' => 'Sanniriya'],
                ['ar' => 'صوفين', 'en' => 'Sufin'],
                ['ar' => 'عرب أبو فردة', 'en' => "Arab Abu Farda"],
                ['ar' => 'عرب الرماضين الجنوبي', 'en' => 'Arab ar-Ramadin al-Janubi'],
                ['ar' => 'عزبة الأشقر', 'en' => "'Izbat al-Ashqar"],
                ['ar' => 'عزبة الطبيب', 'en' => "'Izbat at-Tabib"],
                ['ar' => 'عزبة جلعود', 'en' => "'Izbat Jalloud"],
                ['ar' => 'عزبة سلمان', 'en' => "'Izbat Salman"],
                ['ar' => 'عزون', 'en' => "'Azzun"],
                ['ar' => 'عزون عتمة', 'en' => "'Azzun 'Atma"],
                ['ar' => 'عسلة', 'en' => "'Asla"],
                ['ar' => 'فرعتا', 'en' => "Far'ata"],
                ['ar' => 'فلامية', 'en' => 'Falamiya'],
                ['ar' => 'قلقيلية-وسط البلد', 'en' => 'Qalqilya - Downtown'],
                ['ar' => 'كفر ثلث', 'en' => 'Kafr Thulth'],
                ['ar' => 'كفر قدوم', 'en' => 'Kafr Qaddum'],
                ['ar' => 'كفر لاقف', 'en' => 'Kafr Laqif'],
                ['ar' => 'مدينة قلقيلية', 'en' => 'Qalqilya City'],
                ['ar' => 'مدينة قلقيلية−حي كفر سابا', 'en' => 'Qalqilya City - Kfar Saba Neighborhood'],
                ['ar' => 'وادي الرشا', 'en' => 'Wadi ar-Rasha'],
            ],
            // نابلس
            'نابلس' => [
                ['ar' => 'إجنسنيا', 'en' => 'Ijnisinya'],
                ['ar' => 'الباذان', 'en' => 'Al-Badhan'],
                ['ar' => 'الساوية', 'en' => 'As-Sawiya'],
                ['ar' => 'الطور', 'en' => 'At-Tur'],
                ['ar' => 'العقربانية', 'en' => 'Al-Aqrabaniya'],
                ['ar' => 'اللبن الشرقية', 'en' => 'Al-Lubban ash-Sharqiya'],
                ['ar' => 'الناقورة', 'en' => 'An-Naqura'],
                ['ar' => 'النصارية', 'en' => 'An-Nassariya'],
                ['ar' => 'أودلا', 'en' => 'Odala'],
                ['ar' => 'أوصرين', 'en' => 'Osarin'],
                ['ar' => 'برقة', 'en' => 'Burqa'],
                ['ar' => 'بورين', 'en' => 'Burin'],
                ['ar' => 'بيتا', 'en' => 'Beita'],
                ['ar' => 'بيت إمرين', 'en' => 'Bayt Imrin'],
                ['ar' => 'بيت إيبا', 'en' => 'Bayt Iba'],
                ['ar' => 'بيت حسن', 'en' => 'Bayt Hassan'],
                ['ar' => 'بيت دجن', 'en' => 'Bayt Dajan'],
                ['ar' => 'بيت فوريك', 'en' => 'Beit Furik'],
                ['ar' => 'بيت وزن', 'en' => 'Bayt Wazan'],
                ['ar' => 'تلفيت', 'en' => 'Talfit'],
                ['ar' => 'جالود', 'en' => 'Jalud'],
                ['ar' => 'جماعين', 'en' => "Jamma'in"],
                ['ar' => 'جوريش', 'en' => 'Jurish'],
                ['ar' => 'حوارة', 'en' => 'Huwara'],
                ['ar' => 'خلة العامود', 'en' => 'Khallat al-Amud'],
                ['ar' => 'دوما', 'en' => 'Duma'],
                ['ar' => 'دير الحطب', 'en' => 'Deir al-Hatab'],
                ['ar' => 'دير شرف', 'en' => 'Deir Sharaf'],
                ['ar' => 'روجيب', 'en' => 'Rujeeb'],
                ['ar' => 'زواتا', 'en' => 'Zawata'],
                ['ar' => 'زيتا جماعين', 'en' => "Zeita Jamma'in"],
                ['ar' => 'سالم', 'en' => 'Salem'],
                ['ar' => 'سبسطية', 'en' => 'Sebastia'],
                ['ar' => 'صرة', 'en' => 'Surra'],
                ['ar' => 'طلوزة', 'en' => 'Taluza'],
                ['ar' => 'عراق بورين', 'en' => 'Iraq Burin'],
                ['ar' => 'عزموط', 'en' => 'Azmut'],
                ['ar' => 'عصيرة الشمالية', 'en' => "'Asira ash-Shamaliya"],
                ['ar' => 'عصيرة القبلية', 'en' => "'Asira al-Qibliya"],
                ['ar' => 'عقربا', 'en' => 'Aqraba'],
                ['ar' => 'عمورية', 'en' => "'Amuriya"],
                ['ar' => 'عورتا', 'en' => 'Awarta'],
                ['ar' => 'عوريف', 'en' => "'Urif"],
                ['ar' => 'عين البيضة (الاغوار)', 'en' => 'Ein al-Beida (Jordan Valley)'],
                ['ar' => 'عينبوس', 'en' => "'Ainabus"],
                ['ar' => 'عين شبلي', 'en' => "'Ain Shibli"],
                ['ar' => 'قبلان', 'en' => 'Qabalan'],
                ['ar' => 'قريوت', 'en' => 'Qaryut'],
                ['ar' => 'قصرة', 'en' => 'Qusra'],
                ['ar' => 'قوصين', 'en' => 'Qusin'],
                ['ar' => 'كفر قليل', 'en' => 'Kafr Qalil'],
                ['ar' => 'مادما', 'en' => 'Madama'],
                ['ar' => 'مجدل بني فاضل', 'en' => 'Majdal Bani Fadil'],
                ['ar' => 'مخيم عين بيت الماء', 'en' => 'Ein Beit al-Maa Camp'],
                ['ar' => 'نابلس - مدينة نابلس', 'en' => 'Nablus - Nablus City'],
                ['ar' => 'إسكان روجيب', 'en' => 'Rujeib Housing'],
                ['ar' => 'الاكاديمية', 'en' => 'The Academy'],
                ['ar' => 'البلدة القديمة', 'en' => 'Old City'],
                ['ar' => 'الجامعه القديمة', 'en' => 'Old University'],
                ['ar' => 'الجبل الجنوبي', 'en' => 'Southern Mountain'],
                ['ar' => 'الجبل الشمالي', 'en' => 'Northern Mountain'],
                ['ar' => 'الجنيد', 'en' => 'Al-Junied'],
                ['ar' => 'الدوار', 'en' => 'The Roundabout'],
                ['ar' => 'السوق الشرقي', 'en' => 'Eastern Market'],
                ['ar' => 'الضاحية', 'en' => 'Al-Dahiya'],
                ['ar' => 'العامرية', 'en' => 'Al-Amiriya'],
                ['ar' => 'العين', 'en' => 'Al-Ein'],
                ['ar' => 'المخفية', 'en' => 'Al-Makhfiyya'],
                ['ar' => 'المساكن الشعبية', 'en' => 'Public Housing'],
                ['ar' => 'المعاجين', 'en' => 'Al-Ma\'ajeen'],
                ['ar' => 'المنطق الصناعية الشرقية', 'en' => 'Eastern Industrial Zone'],
                ['ar' => 'بكير', 'en' => 'Bukir'],
                ['ar' => 'بلاطة', 'en' => 'Balata'],
                ['ar' => 'راس العين', 'en' => 'Ras al-Ein'],
                ['ar' => 'رفيديا', 'en' => 'Rafidia'],
                ['ar' => 'شارع 15', 'en' => 'Street 15'],
                ['ar' => 'شارع 16', 'en' => 'Street 16'],
                ['ar' => 'شارع احمد الشكعة', 'en' => 'Ahmad Al-Shakaa Street'],
                ['ar' => 'شارع الاتحاد', 'en' => 'Ittihad Street'],
                ['ar' => 'شارع التعاون', 'en' => 'Taawun Street'],
                ['ar' => 'شارع الحسبة', 'en' => 'Hasba Street'],
                ['ar' => 'شارع الرازي', 'en' => 'Razi Street'],
                ['ar' => 'شارع السكة', 'en' => 'Railway Street'],
                ['ar' => 'شارع القدس', 'en' => 'Jerusalem Street'],
                ['ar' => 'شارع المدارس', 'en' => 'Schools Street'],
                ['ar' => 'شارع المنتزه', 'en' => 'Park Street'],
                ['ar' => 'شارع تل', 'en' => 'Tell Street'],
                ['ar' => 'شارع جمال عبد الناصر', 'en' => 'Gamal Abdel Nasser Street'],
                ['ar' => 'شارع حطين', 'en' => 'Hittin Street'],
                ['ar' => 'شارع حيفا', 'en' => 'Haifa Street'],
                ['ar' => 'شارع سفيان', 'en' => 'Sufyan Street'],
                ['ar' => 'شارع شويترة', 'en' => 'Shweitra Street'],
                ['ar' => 'شارع صلاح الدين', 'en' => 'Salah al-Din Street'],
                ['ar' => 'شارع طولكرم', 'en' => 'Tulkarm Street'],
                ['ar' => 'شارع عصيرة', 'en' => "'Asira Street"],
                ['ar' => 'شارع عمان', 'en' => 'Amman Street'],
                ['ar' => 'شارع عمر المختار', 'en' => 'Omar al-Mukhtar Street'],
                ['ar' => 'شارع غرناطة', 'en' => 'Granada Street'],
                ['ar' => 'شارع فلسطين', 'en' => ' Palestine Street'],
                ['ar' => 'شارع فيصل', 'en' => ' Faisal Street'],
                ['ar' => 'شارع يافا', 'en' => ' Jaffa Street'],
                ['ar' => 'عسكر', 'en' => ' Askar'],
                ['ar' => 'فطاير', 'en' => ' Ftayer'],
                ['ar' => 'قرية تل', 'en' => ' Tell Village'],
                ['ar' => 'مخيم بلاطة', 'en' => ' Balata Camp'],
                ['ar' => 'مخيم عسكر', 'en' => ' Askar Camp'],
                ['ar' => 'نابلس الجديدة', 'en' => ' New Nablus'],
                ['ar' => 'نابلس-شارع العدل', 'en' => ' Justice Street'],
                ['ar' => 'نابلس-وسط البلد', 'en' => ' Downtown Nablus'],
                ['ar' => 'نابلس', 'en' => 'Nablus'],
                ['ar' => 'نابلس−شارع ابن رشد', 'en' => 'Nablus - Ibn Rushd Street'],
                ['ar' => 'نصف جبيل', 'en' => 'Nisf Jubeil'],
                ['ar' => 'ياصيد', 'en' => "Ya'sid"],
                ['ar' => 'يتما', 'en' => 'Yatma'],
            ],
        ];

        $created = 0; $updated = 0; $updatedTranslations = 0; $missingCities = [];

        foreach ($data as $cityArName => $villages) {
            // البحث عن المدينة داخل فلسطين باسمها العربي
            $city = City::where('country_id', $palestine->id)
                ->whereTranslation('name', $cityArName, 'ar')
                ->first();

            if (!$city) {
                $missingCities[] = $cityArName;
                continue;
            }

            foreach ($villages as $entry) {
                // يدعم إما نص عربي بسيط أو مصفوفة ['ar' => '...', 'en' => '...']
                $vArName = is_array($entry) ? ($entry['ar'] ?? null) : $entry;
                $vEnName = is_array($entry) ? ($entry['en'] ?? null) : null;

                // تجاهل الإدخال الفارغ تماماً
                if (!$vArName && !$vEnName) {
                    continue;
                }

                // ابحث أولاً بالاسم العربي إن توفر، وإلا جرّب الإنجليزي لمنع التكرار
                $existing = null;
                if ($vArName) {
                    $existing = Village::where('city_id', $city->id)
                        ->whereTranslation('name', $vArName, 'ar')
                        ->first();
                }
                if (!$existing && $vEnName) {
                    $existing = Village::where('city_id', $city->id)
                        ->whereTranslation('name', $vEnName, 'en')
                        ->first();
                }

                if ($existing) {
                    // تأكيد الربط بالمدينة الصحيحة وتحديث الترجمات
                    $existing->city_id = $city->id;
                    if ($vArName) {
                        $existing->translateOrNew('ar')->name = $vArName;
                    }
                    if ($vEnName) {
                        $existing->translateOrNew('en')->name = $vEnName;
                    }
                    $existing->save();
                    $updated++;
                    if ($vEnName) { $updatedTranslations++; }
                    continue;
                }

                // إنشاء سجل جديد مع الترجمات المتاحة
                $village = new Village();
                $village->city_id = $city->id;
                if ($vArName) { $village->translateOrNew('ar')->name = $vArName; }
                if ($vEnName) { $village->translateOrNew('en')->name = $vEnName; }
                $village->save();
                $created++;
            }
        }

        if (!empty($missingCities)) {
            $this->command?->warn('لم يتم العثور على المدن التالية داخل فلسطين: ' . implode(', ', $missingCities));
        }

        $this->command?->info("تم إدراج/تحديث القرى متعددة اللغات. المضاف: {$created}، المحدّث: {$updated}، ترجمات محدّثة: {$updatedTranslations}");
    }
}
